{% set name = "sphinx-better-theme" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-better-theme-{{ version }}.tar.gz
  sha256: 420570d80d8cab25b35cef2b79619104675777dff5a23deebe9ba2191d48c1ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - better
    - pip
  run:
    - python

test:
  imports:
    - better
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/irskep/sphinx-better-theme
  summary: A nice-looking, customizable Sphinx theme
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gb119
